### ISSUE TITLE
Quotes could have href as well

### ISSUE THREAD

**Issue by reveurmichael** [open-academy/machine-learning#22]
https://computational-discovery-on-jupyter.github.io/Computational-Discovery-on-Jupyter/index.html
https://github.com/Computational-Discovery-on-Jupyter/Computational-Discovery-on-Jupyter

**Comment by zhangqi444** [comment]
This is supported by jupyterbook by default. you can try below

\```{epigraph}
[13%](https://venturebeat.com/2019/07/19/why-do-87-of-data-science-projects-never-make-it-into-production/)

--  [13%](https://venturebeat.com/2019/07/19/why-do-87-of-data-science-projects-never-make-it-into-production/)
\```
